### ISSUE TITLE
Fabrica SW Upgrade

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#716]
Some notes for the next Fabrica upgrade. Using this as a clearinghouse for tasks involved in upgrading since it will be done again soon and there are continuing tasks and issues.

Some documentation:

- The [previous epic](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1603) for documentation purposes.
- The [manual testing checklist](https://docs.google.com/document/d/18wIQyKQbiX20cOvsZclVya0CB3uGH0AUMWsuQ3fbZrs/edit?usp=sharing).
- A list of [resources](https://docs.google.com/document/d/1qioq797ev6Pp-NB3tBAAbrTJZMtvbVxt_T_vKRupWbc/edit?usp=sharing).

Tasks involved:

- [ ] Upgrade to at least the next LTS release (3.20).  If that goes well we can go beyond to 3.24, perhaps 3.28.  This includes:
    - [x] Upgrade to Node v18. That should work.  If not, upgrade node to the version in the [ember/node compatibility matrix](https://github.com/ember-cli/ember-cli/blob/master/docs/node-support.md).
    - [ ] Upgrade ember core modules including any module-specific migrations that may be needed.
    - [ ] Upgrade 3rd-party modules including any module-specific migrations that may be needed.
- [ ] Address deprecations in each stage: yarn install, Ember build(s), and Ember runtime uses ember-cli-deprecation-workflow.
- [ ] Address unused modules.
- [ ] Address dependabot security notices (yarn resolutions).
- [ ] Run `npx browserslist@latest --update-db` to get the latest browser capabilities which are used in the build.  This updates the lockfile with the latest caniuse-lite database.
- [ ] Address GitHub workflows, and at a minimum any deprecation notices there.
- [ ] Address any incompatibilities with the Vercel build.
- [ ] Ember Classic to Ember Octane migration must be planned for and dealt with before moving to v4.0.0.  This includes
    - [ ] Glimmer components.
    - [ ] Javascript to Typescript.
    - [ ] Ember-data-model-fragments is said to have problems with Ember Octane.
- [ ] Manual testing of core functionality in addition to test suites.
- [ ] Check Sentry for new fabrica issues.
- [ ] Remember to update the release number in package.json.

Additional items:

- [ ] Upgrade the test suites.
    - [ ] Cypress data factories?
    - [ ] Cypress component testing.
    - [ ] Better testing of Fabrica core functionality.
    - [ ] Cross-browser testing (can be done in cypress or browserstack.io, and manual test checklist).
- [ ] Considerations for moving to another framework?
- [ ] Address build warnings: ['loose options' warnings](https://vercel.com/datacite/bracco/CQmVEMwRQBrv4MHyj8vZAt1EuWCG) in particular.
- [ ] Better error handling in Fabrica forms.
    - [ ] Address all forms to make sure they report errors to the user.  Many don't. 
- [ ] Auto update for release on the Fabrica 'about' page (done by updating the release number in package.json).  Maybe include the sha?

**Comment by svogt0511** [comment]
This is outdated.
