### ISSUE TITLE
Upgrade Fabrica to Ember v3.24

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#735]
Updates Fabrica from v3.16 to v3.24.  (Not there was a 3 week break due to vacation and the team retreat, June 25 - July 16.)

VERCEL DEPLOYMENT: https://bracco-3c632crit-datacite.vercel.app/

MANUAL TESTING CHECKLIST: https://docs.google.com/document/d/18wIQyKQbiX20cOvsZclVya0CB3uGH0AUMWsuQ3fbZrs/edit

**PROJECT TASKS:**

- [x] #751 - Why doesn't 'citation' appear on the 'DOI Show' page
- [x] #741 - Update the GitHub ReadMe.md and any other documentation.
- [x] #768 
- [x] #756 - Selecting different tabs does not consistently move the caret when logged in as a Member or Repository
- [x] #745 - Check for unused modules and remove them if possible. 
- [x] #742 - Resolve applicable security notices.
- [x] #749 - Fix 'Calling set on destroyed object' issues
- [x] #750 - 'Refresh circle' missing in add forms.
- [X] Already up to node 18 (as part of #738).
- [X] Upgrade Ember core is to V3.24.
- [X] Implement a temporary workaround to build error due to deprecation of openssl in node 18 (ERR_OSSL_EVP_UNSUPPORTED).  (See "Issues...", below.)
- [x] Update third-party (non-core) modules where possible.
- [x] #748 - Codemods that are not part of the core upgrade process. (See #748 for a more detailed description of what had to be done.)
    - [x] In the process of debugging Fabrica forms and adding codemods to Fabrica forms as a part of this upgrade.  These are necessary due to changes to bootstrap/ember-bootstrap/ember-power-select/ember-ember-bootstrap-power-select, in particular, bsButtons and bsform elements, especially power-select.  Sometimes you will see warnings in the browser dev console for these things.
    - [x] Added a postinstall patch to the ember-bootstrap-power-select module to fix a bug that prevented onKeydown from invoking createOnEnter for many of the power-select fields in DataCite forms.  This bug has been fixed in ember-bootstrap-power-select v5 (we use v4), but migration from v4 to v5 would require a migration from bootstrap 3 to bootstrap 4 (and possibly bootstrap 5), which could require a lot more work.  The patch is sufficient for now and can be easily removed once we decide to upgrade bootstrap.
    - [x] Checking into why Fabrica forms don't seem to enforce required fields any more (this has been a problem for a while).
- [x] #757
- [x] #756 

**TESTING TASKS:**

- [x] #744  -  Manual testing based on the manual testing checklist.
- [x] Address any issues that come from the manual testing.
- [x] #759 - Update Cypress to v12
- [x] Run current test suites:
    - [x] Qunit/Polly test suite - make sure it runs - do the migration including migration codemods (See the [ember-qunit migration guide](https://github.com/emberjs/ember-qunit/blob/HEAD/docs/migration.md), v4 to v5)
    - [x] Cypress test suite - make sure it runs.
    - [x] Add/delete/modify tests as necessary.
- [x] Cypress test data needs to be reworked.  Restructuring/cleanup test data. (See 'Future')
    - [x] #743 - Delete contacts created for test runs.

**LUPO TASKS:**

- [x] Provider IDs returned as part of relationships in /contacts requests need to always be lowercase. ([Lupo PR#993](https://github.com/datacite/lupo/pull/993))

**PRE-DEPLOYMENT TASKS**

- [x] Review by other development group members
- [x] Acceptance testing - by development and engagement team members
- [x] Address any issues that come from review/acceptance testing.

**POST-DEPLOYMENT TASKS**

- [ ] Update Fabrica support issues - answer/close/consolidate/prioritize items where possible.

## RESOURCES

- [Fabrica Software Upgrade Guide](https://docs.google.com/document/d/1qioq797ev6Pp-NB3tBAAbrTJZMtvbVxt_T_vKRupWbc/edit?usp=sharing)
- [Fabrica Manual Testing Checklist](https://docs.google.com/document/d/18wIQyKQbiX20cOvsZclVya0CB3uGH0AUMWsuQ3fbZrs/edit?usp=sharing)
- [Epic: Upgrade Fabrica to Ember v3.24](https://github.com/datacite/bracco/issues/735)
- [Epic: Upgrade Fabrica to Ember v3.28/Octane](https://github.com/datacite/bracco/issues/760)
- [Epic: Upgrade Fabrica to Ember v4.X/Octane](https://github.com/datacite/bracco/issues/761)
- [Fabrica Implementation Notes](https://docs.google.com/document/d/1zuORV1bLnYNMOwPhNflYsLVzk6M_IRGfA6jtlyHX1qE/edit?usp=sharing)
